export const levels = [
  {
    code: "A1",
    label: "A1 · Superviviente",
    objective:
      "Leer y entender frases simples sobre temas cotidianos: presentarse, familia, rutina, lugares.",
  },
  {
    code: "A2",
    label: "A2 · Básico",
    objective:
      "Leer historias cortas con pasado y futuro, y seguir una narración simple.",
  },
  {
    code: "B1",
    label: "B1 · Intermedio",
    objective:
      "Leer cuentos adaptados y textos de uso cotidiano sin depender de traducción constante.",
  },
  {
    code: "B2",
    label: "B2 · Intermedio alto",
    objective:
      "Leer prensa sencilla, ensayos cortos y literatura adaptada extensa con fluidez razonable.",
  },
  {
    code: "C1",
    label: "C1 · Avanzado",
    objective:
      "Leer literatura original corta y textos especializados con comprensión matizada.",
  },
  {
    code: "C2",
    label: "C2 · Maestría",
    objective:
      "Leer literatura clásica, poesía y textos académicos sin adaptar, con apreciación estilística plena.",
  },
];

export const lessonsIndex = [
  {
    slug: "alphabet",
    file: "lesson-01-alphabet.html",
    level: "A1",
    order: 2,
    title: "Alfabeto y fonética",
    grammarLabel: "Acento tónico",
    summary: "El alfabeto cirílico, el acento tónico y palabras cognadas fáciles de leer.",
  },
  {
    slug: "pronouns-questions",
    file: "lesson-02-pronouns-questions.html",
    level: "A1",
    order: 3,
    title: "Pronombres y preguntas básicas",
    grammarLabel: "Verbo ser/estar omitido",
    summary: "Pronombres personales, el verbo быть omitido, y кто/что/где/как.",
  },
  {
    slug: "gender-number",
    file: "lesson-03-gender-number.html",
    level: "A1",
    order: 4,
    title: "Género y plural de sustantivos",
    grammarLabel: "Género y plural",
    summary: "Masculino, femenino y neutro; plural regular, la regla ortográfica -и y plurales irregulares.",
  },
  {
    slug: "adjective-endings",
    file: "lesson-34-adjective-endings.html",
    level: "A1",
    order: 5,
    title: "Terminaciones del adjetivo por género",
    grammarLabel: "Terminaciones del adjetivo",
    summary: "Cómo concuerdan los adjetivos en género y número con el sustantivo: los grupos -ый y -ий.",
  },
  {
    slug: "routine",
    file: "lesson-04-routine.html",
    level: "A1",
    order: 7,
    title: "Rutina diaria",
    grammarLabel: "Verbos en presente",
    summary: "Verbos en presente, conjugaciones, días de la semana y la hora.",
  },
  {
    slug: "places-shopping",
    file: "lesson-05-places-shopping.html",
    level: "A1",
    order: 8,
    title: "Lugares y compras",
    grammarLabel: "Preposiciones в / на",
    summary: "Preposiciones в/на, números hasta 100 y vocabulario de tienda y ciudad.",
  },
  {
    slug: "review-a1",
    file: "lesson-10-review-a1.html",
    level: "A1",
    order: 15,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A1: todo el nivel combinado en un texto final.",
  },
  {
    slug: "greetings",
    file: "lesson-06-greetings.html",
    level: "A1",
    order: 9,
    title: "Saludos",
    grammarLabel: "Registro formal/informal",
    summary: "Práctica extra: saludos formales e informales, y despedidas.",
  },
  {
    slug: "introductions",
    file: "lesson-07-introductions.html",
    level: "A1",
    order: 11,
    title: "Presentarse: cómo te llamas",
    grammarLabel: "«Меня зовут»",
    summary: "Práctica extra: la construcción «меня зовут» y tu edad.",
  },
  {
    slug: "profession-origin",
    file: "lesson-35-profession-origin.html",
    level: "A1",
    order: 12,
    title: "Presentarse: profesión y ciudad de origen",
    grammarLabel: "«Я + profesión»",
    summary: "Práctica extra: «я + profesión» y «я из + ciudad» en genitivo.",
  },
  {
    slug: "family",
    file: "lesson-08-family.html",
    level: "A1",
    order: 13,
    title: "Familia",
    grammarLabel: "Posesivos",
    summary: "Práctica extra: vocabulario de familia y los posesivos мой/моя/моё.",
  },
  {
    slug: "numbers",
    file: "lesson-09-numbers.html",
    level: "A1",
    order: 14,
    title: "Números del 1 al 10",
    grammarLabel: "Números y sustantivos",
    summary: "Práctica extra: contar del 1 al 10 y cómo cambian los sustantivos.",
  },
  {
    slug: "a1-vocab-1",
    file: "lesson-29-a1-vocab-1.html",
    level: "A1",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 3, con ejercicio de completar.",
  },
  {
    slug: "a1-vocab-2",
    file: "lesson-30-a1-vocab-2.html",
    level: "A1",
    order: 6,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 4 a 6, con ejercicio de completar.",
  },
  {
    slug: "a1-vocab-3",
    file: "lesson-31-a1-vocab-3.html",
    level: "A1",
    order: 10,
    type: "vocabulary",
    title: "Vocabulario 3",
    summary: "Vocabulario nuevo que aparece en las lecciones 7 a 10, con ejercicio de completar.",
  },
  {
    slug: "simple-past",
    file: "lesson-11-simple-past.html",
    level: "A2",
    order: 2,
    title: "Pasado simple",
    grammarLabel: "Pasado simple",
    summary: "Formación del pasado, concordancia por género y marcadores temporales.",
  },
  {
    slug: "future-plans",
    file: "lesson-12-future-plans.html",
    level: "A2",
    order: 3,
    title: "Futuro simple",
    grammarLabel: "Futuro simple",
    summary: "Futuro simple con verbos perfectivos: acciones puntuales o completas.",
  },
  {
    slug: "compound-future",
    file: "lesson-36-compound-future.html",
    level: "A2",
    order: 4,
    title: "Futuro compuesto",
    grammarLabel: "Futuro compuesto",
    summary: "быть conjugado + infinitivo imperfectivo: acciones que duran o se repiten.",
  },
  {
    slug: "genitive-accusative",
    file: "lesson-13-genitive-accusative.html",
    level: "A2",
    order: 5,
    title: "Caso genitivo",
    grammarLabel: "Caso genitivo",
    summary: "Posesión, cantidad y negación de existencia con нет.",
  },
  {
    slug: "accusative-case",
    file: "lesson-37-accusative-case.html",
    level: "A2",
    order: 6,
    title: "Caso acusativo",
    grammarLabel: "Caso acusativo",
    summary: "El objeto directo del verbo: femeninos que cambian, masculinos que no.",
  },
  {
    slug: "a2-vocab-1",
    file: "lesson-32-a2-vocab-1.html",
    level: "A2",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 3, con ejercicio de completar.",
  },
  {
    slug: "descriptions-comparisons",
    file: "lesson-14-descriptions-comparisons.html",
    level: "A2",
    order: 8,
    title: "Descripciones y comparaciones",
    grammarLabel: "Comparativos y superlativos",
    summary: "Comparativos, superlativos y vocabulario de familia extendida.",
  },
  {
    slug: "everyday-narrative",
    file: "lesson-15-everyday-narrative.html",
    level: "A2",
    order: 9,
    title: "Narrativa cotidiana",
    grammarLabel: "Conectores narrativos",
    summary: "Conectores narrativos y discurso directo para contar el día a día.",
  },
  {
    slug: "a2-vocab-2",
    file: "lesson-33-a2-vocab-2.html",
    level: "A2",
    order: 7,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 4 y 5, con ejercicio de completar.",
  },
  {
    slug: "review-a2",
    file: "lesson-16-review-a2.html",
    level: "A2",
    order: 10,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A2: una historia completa que integra todo el nivel.",
  },
  {
    slug: "b1-vocab-1",
    file: "lesson-44-b1-vocab-1.html",
    level: "B1",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 5, con ejercicio de completar.",
  },
  {
    slug: "verbal-aspect",
    file: "lesson-17-verbal-aspect.html",
    level: "B1",
    order: 2,
    title: "Aspecto verbal",
    grammarLabel: "Aspecto verbal",
    summary: "Perfectivo vs. imperfectivo: la diferencia entre proceso y acción completada.",
  },
  {
    slug: "dative-instrumental-cases",
    file: "lesson-18-dative-instrumental-cases.html",
    level: "B1",
    order: 3,
    title: "Caso dativo: ¿a quién?",
    grammarLabel: "Caso dativo",
    summary: "El destinatario de la acción, con verbos como помогать y звонить.",
  },
  {
    slug: "instrumental-case",
    file: "lesson-38-instrumental-case.html",
    level: "B1",
    order: 4,
    title: "Caso instrumental: ¿con qué?",
    grammarLabel: "Caso instrumental",
    summary: "El instrumento o la compañía: писать ручкой, идти с другом.",
  },
  {
    slug: "prepositional-case",
    file: "lesson-40-prepositional-case.html",
    level: "B1",
    order: 5,
    title: "Caso preposicional: ¿dónde? ¿de qué?",
    grammarLabel: "Caso preposicional",
    summary: "El sexto caso: в/на de lugar y о/об de tema, siempre con preposición.",
  },
  {
    slug: "reflexive-verbs",
    file: "lesson-41-reflexive-verbs.html",
    level: "B1",
    order: 6,
    title: "Verbos reflexivos: -ся / -сь",
    grammarLabel: "Verbos reflexivos -ся",
    summary: "Reflexivo, recíproco y verbos que solo existen con -ся: одеваться, нравиться, начинаться.",
  },
  {
    slug: "b1-vocab-2",
    file: "lesson-45-b1-vocab-2.html",
    level: "B1",
    order: 7,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 6 a 12, con ejercicio de completar.",
  },
  {
    slug: "motion-verbs",
    file: "lesson-19-motion-verbs.html",
    level: "B1",
    order: 8,
    title: "Verbos de movimiento: unidireccionales y multidireccionales",
    grammarLabel: "Verbos de movimiento",
    summary: "идти/ходить, ехать/ездить, лететь/летать: una vez vs. hábito.",
  },
  {
    slug: "motion-verb-prefixes",
    file: "lesson-39-motion-verb-prefixes.html",
    level: "B1",
    order: 9,
    title: "Prefijos de dirección con verbos de movimiento",
    grammarLabel: "Prefijos de movimiento",
    summary: "при-, у- y вы-: llegar, partir y salir, a pie o en vehículo.",
  },
  {
    slug: "adapted-literary-reading",
    file: "lesson-20-adapted-literary-reading.html",
    level: "B1",
    order: 10,
    title: "Primeras lecturas literarias",
    grammarLabel: "Pronombre «который»",
    summary: "Introducción a la lectura literaria adaptada y el pronombre который.",
  },
  {
    slug: "opinion-argumentation",
    file: "lesson-21-opinion-argumentation.html",
    level: "B1",
    order: 11,
    title: "Expresar opinión",
    grammarLabel: "Expresiones de opinión",
    summary: "Fórmulas para dar una opinión, de lo coloquial (por-моему) a lo formal (на мой взгляд).",
  },
  {
    slug: "cause-consequence-connectors",
    file: "lesson-43-cause-consequence-connectors.html",
    level: "B1",
    order: 12,
    title: "Conectores de causa y consecuencia",
    grammarLabel: "Causa y consecuencia",
    summary: "так как, из-за того что y поэтому: justificar algo y señalar su consecuencia.",
  },
  {
    slug: "case-summary",
    file: "lesson-42-case-summary.html",
    level: "B1",
    order: 13,
    title: "Los seis casos: resumen y comparación",
    grammarLabel: "Los seis casos",
    summary: "Nominativo, acusativo, genitivo, dativo, instrumental y preposicional, uno al lado del otro.",
  },
  {
    slug: "review-b1",
    file: "lesson-22-review-b1.html",
    level: "B1",
    order: 14,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B1: un cuento adaptado que integra todo el nivel.",
  },
  {
    slug: "b2-vocab-1",
    file: "lesson-46-b2-vocab-1.html",
    level: "B2",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 3, con ejercicio de completar.",
  },
  {
    slug: "participles-gerunds",
    file: "lesson-23-participles-gerunds.html",
    level: "B2",
    order: 2,
    title: "Participios y gerundios",
    grammarLabel: "Participios y gerundios",
    summary: "Formación de participios activos, pasivos y gerundios (деепричастия).",
  },
  {
    slug: "indirect-speech",
    file: "lesson-24-indirect-speech.html",
    level: "B2",
    order: 3,
    title: "Estilo indirecto",
    grammarLabel: "Discurso indirecto",
    summary: "Transformar discurso directo a indirecto con verbos de comunicación.",
  },
  {
    slug: "press-informative-texts",
    file: "lesson-25-press-informative-texts.html",
    level: "B2",
    order: 4,
    title: "Prensa y textos informativos",
    grammarLabel: "Sustantivos deverbales",
    summary: "Vocabulario de noticias y sustantivos formados a partir de verbos.",
  },
  {
    slug: "b2-vocab-2",
    file: "lesson-47-b2-vocab-2.html",
    level: "B2",
    order: 5,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 4 y 5, con ejercicio de completar.",
  },
  {
    slug: "extended-adapted-literature",
    file: "lesson-26-extended-adapted-literature.html",
    level: "B2",
    order: 6,
    title: "Literatura adaptada extensa",
    grammarLabel: "Conectores subordinantes",
    summary: "Fragmento narrativo más largo con oraciones subordinadas complejas.",
  },
  {
    slug: "register-nuances",
    file: "lesson-27-register-nuances.html",
    level: "B2",
    order: 7,
    title: "Registro y matices",
    grammarLabel: "Neutro / coloquial / literario",
    summary: "Neutro, coloquial y literario: comparar el mismo concepto en tres registros.",
  },
  {
    slug: "review-b2",
    file: "lesson-28-review-b2.html",
    level: "B2",
    order: 8,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B2: un texto extenso de cierre para todo el nivel.",
  },
  {
    slug: "c1-vocab-1",
    file: "lesson-48-c1-vocab-1.html",
    level: "C1",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 4, con ejercicio de completar.",
  },
  {
    slug: "verb-government",
    file: "lesson-49-verb-government.html",
    level: "C1",
    order: 2,
    title: "Régimen verbal: verbos con preposición fija",
    grammarLabel: "Régimen verbal",
    summary: "гордиться, увлекаться, заботиться о, верить в: cada verbo con su preposición y caso fijos.",
  },
  {
    slug: "verb-prefixes-meaning",
    file: "lesson-50-verb-prefixes-meaning.html",
    level: "C1",
    order: 3,
    title: "Prefijos verbales y cambio de significado",
    grammarLabel: "Prefijos y significado",
    summary: "Cómo пере-, под-, о-, за-, вы- y до- cambian por completo el sentido de un verbo.",
  },
  {
    slug: "conditional-sentences",
    file: "lesson-51-conditional-sentences.html",
    level: "C1",
    order: 4,
    title: "Oraciones condicionales: если / если бы",
    grammarLabel: "Condicionales",
    summary: "Condicional real (если) vs. irreal (если бы + бы): cómo hablar de hipótesis.",
  },
  {
    slug: "discourse-particles",
    file: "lesson-52-discourse-particles.html",
    level: "C1",
    order: 5,
    title: "Partículas discursivas: же, ведь, -то, вот, вон",
    grammarLabel: "Partículas discursivas",
    summary: "Las palabritas que hacen sonar natural el ruso hablado: énfasis, obviedad, señalamiento.",
  },
  {
    slug: "c1-vocab-2",
    file: "lesson-53-c1-vocab-2.html",
    level: "C1",
    order: 6,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 5 a 9, con ejercicio de completar.",
  },
  {
    slug: "idioms",
    file: "lesson-54-idioms.html",
    level: "C1",
    order: 7,
    title: "Fraseología: idioms de uso frecuente",
    grammarLabel: "Fraseología",
    summary: "Seis idioms rusos frecuentes, de «colgar fideos en las orejas» a «matar dos liebres».",
  },
  {
    slug: "academic-register",
    file: "lesson-55-academic-register.html",
    level: "C1",
    order: 8,
    title: "Registro académico: voz pasiva y construcciones impersonales",
    grammarLabel: "Registro académico",
    summary: "считается, известно, verbos en -ся: cómo suena un texto científico o académico.",
  },
  {
    slug: "short-story-reading",
    file: "lesson-56-short-story-reading.html",
    level: "C1",
    order: 9,
    title: "Lectura: un cuento corto",
    grammarLabel: "Matices literarios",
    summary: "Un cuento corto de cierre, centrado en el vocabulario que muestra emoción sin explicarla.",
  },
  {
    slug: "review-c1",
    file: "lesson-57-review-c1.html",
    level: "C1",
    order: 10,
    title: "Repaso integrador",
    summary: "Proyecto de cierre C1: una historia que integra los cinco pilares del nivel.",
  },
  {
    slug: "c2-vocab-1",
    file: "lesson-58-c2-vocab-1.html",
    level: "C2",
    order: 1,
    type: "vocabulary",
    title: "Vocabulario 1",
    summary: "Vocabulario nuevo que aparece en las lecciones 1 a 3, con ejercicio de completar.",
  },
  {
    slug: "19th-century-literary-russian",
    file: "lesson-59-19th-century-literary-russian.html",
    level: "C2",
    order: 2,
    title: "Ruso literario del siglo XIX: vocabulario y sintaxis elevada",
    grammarLabel: "Ruso literario clásico",
    summary: "Очи, уста, сей, дабы: el vocabulario paralelo de la literatura del siglo XIX.",
  },
  {
    slug: "poetry-meter-rhyme",
    file: "lesson-60-poetry-meter-rhyme.html",
    level: "C2",
    order: 3,
    title: "Poesía: métrica, rima y lenguaje poético",
    grammarLabel: "Métrica y rima",
    summary: "Cómo analizar un poema — con «Я вас любил» de Pushkin, texto completo sin adaptar.",
  },
  {
    slug: "irony-subtext",
    file: "lesson-61-irony-subtext.html",
    level: "C2",
    order: 4,
    title: "Ironía, subtexto y registro figurativo",
    grammarLabel: "Ironía y subtexto",
    summary: "Lo que se dice sin decirlo: ironía, подтекст y namёк en la conversación educada.",
  },
  {
    slug: "c2-vocab-2",
    file: "lesson-62-c2-vocab-2.html",
    level: "C2",
    order: 5,
    type: "vocabulary",
    title: "Vocabulario 2",
    summary: "Vocabulario nuevo que aparece en las lecciones 4 a 8, con ejercicio de completar.",
  },
  {
    slug: "word-formation-suffixes",
    file: "lesson-63-word-formation-suffixes.html",
    level: "C2",
    order: 6,
    title: "Formación de palabras: sufijos productivos",
    grammarLabel: "Formación de palabras",
    summary: "-ость, -ник, -ическ(ий): cómo deducir palabras nuevas a partir de raíces conocidas.",
  },
  {
    slug: "colloquialisms-slang",
    file: "lesson-64-colloquialisms-slang.html",
    level: "C2",
    order: 7,
    title: "Coloquialismos y jerga contemporánea",
    grammarLabel: "Jerga contemporánea",
    summary: "Клёво, тусовка, короче: el ruso informal de hoy, frente al registro neutro.",
  },
  {
    slug: "classic-text-reading",
    file: "lesson-65-classic-text-reading.html",
    level: "C2",
    order: 8,
    title: "Lectura extensa: un texto clásico sin adaptar",
    grammarLabel: "Lectura clásica",
    summary: "La fábula completa «Ворона и Лисица» de Krylov, sin adaptar, con glosario de apoyo.",
  },
  {
    slug: "review-c2",
    file: "lesson-66-review-c2.html",
    level: "C2",
    order: 9,
    title: "Repaso integrador",
    summary: "Proyecto de cierre C2: un año de aprendizaje que integra los cinco pilares del nivel.",
  },
];
