export const levels = [
  {
    code: "A1",
    label: "A1 · Superviviente",
    objective:
      "Leer y entender frases simples sobre temas cotidianos: presentarse, familia, rutina, lugares.",
  },
  {
    code: "A2",
    label: "A2 · Básico",
    objective:
      "Leer historias cortas con pasado y futuro, y seguir una narración simple.",
  },
  {
    code: "B1",
    label: "B1 · Intermedio",
    objective:
      "Leer cuentos adaptados y textos de uso cotidiano sin depender de traducción constante.",
  },
  {
    code: "B2",
    label: "B2 · Intermedio alto",
    objective:
      "Leer prensa sencilla, ensayos cortos y literatura adaptada extensa con fluidez razonable.",
  },
  {
    code: "C1",
    label: "C1 · Avanzado",
    objective:
      "Leer literatura original corta y textos especializados con comprensión matizada.",
  },
  {
    code: "C2",
    label: "C2 · Maestría",
    objective:
      "Leer literatura clásica, poesía y textos académicos sin adaptar, con apreciación estilística plena.",
  },
];

export const lessonsIndex = [
  {
    slug: "alphabet",
    file: "lesson-01-alphabet.html",
    level: "A1",
    order: 1,
    title: "Alfabeto y fonética",
    summary: "El alfabeto cirílico, el acento tónico y palabras cognadas fáciles de leer.",
  },
  {
    slug: "pronouns-questions",
    file: "lesson-02-pronouns-questions.html",
    level: "A1",
    order: 2,
    title: "Pronombres y preguntas básicas",
    summary: "Pronombres personales, el verbo быть omitido, y кто/что/где/как.",
  },
  {
    slug: "gender-number",
    file: "lesson-03-gender-number.html",
    level: "A1",
    order: 3,
    title: "Género y número",
    summary: "Masculino, femenino y neutro; plurales regulares y adjetivos básicos.",
  },
  {
    slug: "routine",
    file: "lesson-04-routine.html",
    level: "A1",
    order: 4,
    title: "Rutina diaria",
    summary: "Verbos en presente, conjugaciones, días de la semana y la hora.",
  },
  {
    slug: "places-shopping",
    file: "lesson-05-places-shopping.html",
    level: "A1",
    order: 5,
    title: "Lugares y compras",
    summary: "Preposiciones в/на, números hasta 100 y vocabulario de tienda y ciudad.",
  },
  {
    slug: "review-a1",
    file: "lesson-10-review-a1.html",
    level: "A1",
    order: 10,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A1: todo el nivel combinado en un texto final.",
  },
  {
    slug: "greetings",
    file: "lesson-06-greetings.html",
    level: "A1",
    order: 6,
    title: "Saludos",
    summary: "Práctica extra: saludos formales e informales, y despedidas.",
  },
  {
    slug: "introductions",
    file: "lesson-07-introductions.html",
    level: "A1",
    order: 7,
    title: "Presentarse",
    summary: "Práctica extra: di tu nombre, tu edad y de dónde eres.",
  },
  {
    slug: "family",
    file: "lesson-08-family.html",
    level: "A1",
    order: 8,
    title: "Familia",
    summary: "Práctica extra: vocabulario de familia y los posesivos мой/моя/моё.",
  },
  {
    slug: "numbers",
    file: "lesson-09-numbers.html",
    level: "A1",
    order: 9,
    title: "Números del 1 al 10",
    summary: "Práctica extra: contar del 1 al 10 y cómo cambian los sustantivos.",
  },
  {
    slug: "simple-past",
    file: "lesson-11-simple-past.html",
    level: "A2",
    order: 1,
    title: "Pasado simple",
    summary: "Formación del pasado, concordancia por género y marcadores temporales.",
  },
  {
    slug: "future-plans",
    file: "lesson-12-future-plans.html",
    level: "A2",
    order: 2,
    title: "Futuro y planes",
    summary: "Futuro simple y compuesto, y una introducción a los verbos de movimiento.",
  },
  {
    slug: "genitive-accusative",
    file: "lesson-13-genitive-accusative.html",
    level: "A2",
    order: 3,
    title: "Genitivo y acusativo",
    summary: "Los dos primeros casos gramaticales: posesión, negación y objeto directo.",
  },
  {
    slug: "descriptions-comparisons",
    file: "lesson-14-descriptions-comparisons.html",
    level: "A2",
    order: 4,
    title: "Descripciones y comparaciones",
    summary: "Comparativos, superlativos y vocabulario de familia extendida.",
  },
  {
    slug: "everyday-narrative",
    file: "lesson-15-everyday-narrative.html",
    level: "A2",
    order: 5,
    title: "Narrativa cotidiana",
    summary: "Conectores narrativos y discurso directo para contar el día a día.",
  },
  {
    slug: "review-a2",
    file: "lesson-16-review-a2.html",
    level: "A2",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A2: una historia completa que integra todo el nivel.",
  },
  {
    slug: "verbal-aspect",
    file: "lesson-17-verbal-aspect.html",
    level: "B1",
    order: 1,
    title: "Aspecto verbal",
    summary: "Perfectivo vs. imperfectivo: la diferencia entre proceso y acción completada.",
  },
  {
    slug: "dative-instrumental-cases",
    file: "lesson-18-dative-instrumental-cases.html",
    level: "B1",
    order: 2,
    title: "Dativo e instrumental",
    summary: "Los casos restantes: a quién/para quién, y con qué/con quién.",
  },
  {
    slug: "motion-verbs",
    file: "lesson-19-motion-verbs.html",
    level: "B1",
    order: 3,
    title: "Verbos de movimiento",
    summary: "Unidireccionales vs. multidireccionales, y prefijos verbales básicos.",
  },
  {
    slug: "adapted-literary-reading",
    file: "lesson-20-adapted-literary-reading.html",
    level: "B1",
    order: 4,
    title: "Primeras lecturas literarias",
    summary: "Introducción a la lectura literaria adaptada y el pronombre который.",
  },
  {
    slug: "opinion-argumentation",
    file: "lesson-21-opinion-argumentation.html",
    level: "B1",
    order: 5,
    title: "Opinión y argumentación",
    summary: "Expresar acuerdo, desacuerdo y opinión personal con conectores de causa.",
  },
  {
    slug: "review-b1",
    file: "lesson-22-review-b1.html",
    level: "B1",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B1: un cuento adaptado que integra todo el nivel.",
  },
  {
    slug: "participles-gerunds",
    file: "lesson-23-participles-gerunds.html",
    level: "B2",
    order: 1,
    title: "Participios y gerundios",
    summary: "Formación de participios activos, pasivos y gerundios (деепричастия).",
  },
  {
    slug: "indirect-speech",
    file: "lesson-24-indirect-speech.html",
    level: "B2",
    order: 2,
    title: "Estilo indirecto",
    summary: "Transformar discurso directo a indirecto con verbos de comunicación.",
  },
  {
    slug: "press-informative-texts",
    file: "lesson-25-press-informative-texts.html",
    level: "B2",
    order: 3,
    title: "Prensa y textos informativos",
    summary: "Vocabulario de noticias y sustantivos formados a partir de verbos.",
  },
  {
    slug: "extended-adapted-literature",
    file: "lesson-26-extended-adapted-literature.html",
    level: "B2",
    order: 4,
    title: "Literatura adaptada extensa",
    summary: "Fragmento narrativo más largo con oraciones subordinadas complejas.",
  },
  {
    slug: "register-nuances",
    file: "lesson-27-register-nuances.html",
    level: "B2",
    order: 5,
    title: "Registro y matices",
    summary: "Neutro, coloquial y literario: comparar el mismo concepto en tres registros.",
  },
  {
    slug: "review-b2",
    file: "lesson-28-review-b2.html",
    level: "B2",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B2: un texto extenso de cierre para todo el nivel.",
  },
];
