export const levels = [
  {
    code: "A1",
    label: "A1 · Superviviente",
    objective:
      "Leer y entender frases simples sobre temas cotidianos: presentarse, familia, rutina, lugares.",
  },
  {
    code: "A2",
    label: "A2 · Básico",
    objective:
      "Leer historias cortas con pasado y futuro, y seguir una narración simple.",
  },
  {
    code: "B1",
    label: "B1 · Intermedio",
    objective:
      "Leer cuentos adaptados y textos de uso cotidiano sin depender de traducción constante.",
  },
  {
    code: "B2",
    label: "B2 · Intermedio alto",
    objective:
      "Leer prensa sencilla, ensayos cortos y literatura adaptada extensa con fluidez razonable.",
  },
];

export const lessonsIndex = [
  {
    slug: "alfabeto",
    file: "leccion-05-alfabeto.html",
    level: "A1",
    order: 1,
    title: "Alfabeto y fonética",
    summary: "El alfabeto cirílico, el acento tónico y palabras cognadas fáciles de leer.",
  },
  {
    slug: "pronombres-preguntas",
    file: "leccion-06-pronombres-preguntas.html",
    level: "A1",
    order: 2,
    title: "Pronombres y preguntas básicas",
    summary: "Pronombres personales, el verbo быть omitido, y кто/что/где/как.",
  },
  {
    slug: "genero-numero",
    file: "leccion-07-genero-numero.html",
    level: "A1",
    order: 3,
    title: "Género y número",
    summary: "Masculino, femenino y neutro; plurales regulares y adjetivos básicos.",
  },
  {
    slug: "rutina",
    file: "leccion-08-rutina.html",
    level: "A1",
    order: 4,
    title: "Rutina diaria",
    summary: "Verbos en presente, conjugaciones, días de la semana y la hora.",
  },
  {
    slug: "lugares-compras",
    file: "leccion-09-lugares-compras.html",
    level: "A1",
    order: 5,
    title: "Lugares y compras",
    summary: "Preposiciones в/на, números hasta 100 y vocabulario de tienda y ciudad.",
  },
  {
    slug: "repaso-a1",
    file: "leccion-10-repaso-a1.html",
    level: "A1",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A1: todo el nivel combinado en un texto final.",
  },
  {
    slug: "saludos",
    file: "leccion-01-saludos.html",
    level: "A1",
    order: 7,
    title: "Saludos",
    summary: "Práctica extra: saludos formales e informales, y despedidas.",
  },
  {
    slug: "presentarse",
    file: "leccion-02-presentarse.html",
    level: "A1",
    order: 8,
    title: "Presentarse",
    summary: "Práctica extra: di tu nombre, tu edad y de dónde eres.",
  },
  {
    slug: "familia",
    file: "leccion-03-familia.html",
    level: "A1",
    order: 9,
    title: "Familia",
    summary: "Práctica extra: vocabulario de familia y los posesivos мой/моя/моё.",
  },
  {
    slug: "numeros",
    file: "leccion-04-numeros.html",
    level: "A1",
    order: 10,
    title: "Números del 1 al 10",
    summary: "Práctica extra: contar del 1 al 10 y cómo cambian los sustantivos.",
  },
  {
    slug: "pasado-simple",
    file: "leccion-11-pasado-simple.html",
    level: "A2",
    order: 1,
    title: "Pasado simple",
    summary: "Formación del pasado, concordancia por género y marcadores temporales.",
  },
  {
    slug: "futuro-planes",
    file: "leccion-12-futuro-planes.html",
    level: "A2",
    order: 2,
    title: "Futuro y planes",
    summary: "Futuro simple y compuesto, y una introducción a los verbos de movimiento.",
  },
  {
    slug: "genitivo-acusativo",
    file: "leccion-13-genitivo-acusativo.html",
    level: "A2",
    order: 3,
    title: "Genitivo y acusativo",
    summary: "Los dos primeros casos gramaticales: posesión, negación y objeto directo.",
  },
  {
    slug: "descripciones-comparaciones",
    file: "leccion-14-descripciones-comparaciones.html",
    level: "A2",
    order: 4,
    title: "Descripciones y comparaciones",
    summary: "Comparativos, superlativos y vocabulario de familia extendida.",
  },
  {
    slug: "narrativa-cotidiana",
    file: "leccion-15-narrativa-cotidiana.html",
    level: "A2",
    order: 5,
    title: "Narrativa cotidiana",
    summary: "Conectores narrativos y discurso directo para contar el día a día.",
  },
  {
    slug: "repaso-a2",
    file: "leccion-16-repaso-a2.html",
    level: "A2",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre A2: una historia completa que integra todo el nivel.",
  },
  {
    slug: "aspecto-verbal",
    file: "leccion-17-aspecto-verbal.html",
    level: "B1",
    order: 1,
    title: "Aspecto verbal",
    summary: "Perfectivo vs. imperfectivo: la diferencia entre proceso y acción completada.",
  },
  {
    slug: "casos-dativo-instrumental",
    file: "leccion-18-casos-dativo-instrumental.html",
    level: "B1",
    order: 2,
    title: "Dativo e instrumental",
    summary: "Los casos restantes: a quién/para quién, y con qué/con quién.",
  },
  {
    slug: "verbos-movimiento",
    file: "leccion-19-verbos-movimiento.html",
    level: "B1",
    order: 3,
    title: "Verbos de movimiento",
    summary: "Unidireccionales vs. multidireccionales, y prefijos verbales básicos.",
  },
  {
    slug: "lectura-literaria-adaptada",
    file: "leccion-20-lectura-literaria-adaptada.html",
    level: "B1",
    order: 4,
    title: "Primeras lecturas literarias",
    summary: "Introducción a la lectura literaria adaptada y el pronombre который.",
  },
  {
    slug: "opinion-argumentacion",
    file: "leccion-21-opinion-argumentacion.html",
    level: "B1",
    order: 5,
    title: "Opinión y argumentación",
    summary: "Expresar acuerdo, desacuerdo y opinión personal con conectores de causa.",
  },
  {
    slug: "repaso-b1",
    file: "leccion-22-repaso-b1.html",
    level: "B1",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B1: un cuento adaptado que integra todo el nivel.",
  },
  {
    slug: "participios-gerundios",
    file: "leccion-23-participios-gerundios.html",
    level: "B2",
    order: 1,
    title: "Participios y gerundios",
    summary: "Formación de participios activos, pasivos y gerundios (деепричастия).",
  },
  {
    slug: "estilo-indirecto",
    file: "leccion-24-estilo-indirecto.html",
    level: "B2",
    order: 2,
    title: "Estilo indirecto",
    summary: "Transformar discurso directo a indirecto con verbos de comunicación.",
  },
  {
    slug: "prensa-textos-informativos",
    file: "leccion-25-prensa-textos-informativos.html",
    level: "B2",
    order: 3,
    title: "Prensa y textos informativos",
    summary: "Vocabulario de noticias y sustantivos formados a partir de verbos.",
  },
  {
    slug: "literatura-adaptada-extensa",
    file: "leccion-26-literatura-adaptada-extensa.html",
    level: "B2",
    order: 4,
    title: "Literatura adaptada extensa",
    summary: "Fragmento narrativo más largo con oraciones subordinadas complejas.",
  },
  {
    slug: "registro-matices",
    file: "leccion-27-registro-matices.html",
    level: "B2",
    order: 5,
    title: "Registro y matices",
    summary: "Neutro, coloquial y literario: comparar el mismo concepto en tres registros.",
  },
  {
    slug: "repaso-b2",
    file: "leccion-28-repaso-b2.html",
    level: "B2",
    order: 6,
    title: "Repaso integrador",
    summary: "Proyecto de cierre B2: un texto extenso de cierre para todo el nivel.",
  },
];
