export const lesson = {
  slug: "a1-vocab-1",
  level: "A1",
  type: "vocabulary",
  module: "Vocabulario 1",
  order: 1,
  title: "Vocabulario 1",
  topics: [
    {
      title: "Sustantivos: lugares, personas y cosas",
      vocabulary: [
        { ru: "Город", transliteration: "gorod", es: "Ciudad" },
        { ru: "Центр", transliteration: "tsentr", es: "Centro" },
        { ru: "Отель", transliteration: "otel'", es: "Hotel" },
        { ru: "Кухня", transliteration: "kukhnya", es: "Cocina" },
        { ru: "Люди", transliteration: "lyudi", es: "Gente / Personas" },
        { ru: "Студент", transliteration: "student", es: "Estudiante" },
        { ru: "Врач", transliteration: "vrach", es: "Médico" },
        { ru: "Друг", transliteration: "drug", es: "Amigo" },
        { ru: "Учитель", transliteration: "uchitel'", es: "Maestro / Maestra" },
        { ru: "Турист", transliteration: "turist", es: "Turista" },
        { ru: "Книга", transliteration: "kniga", es: "Libro" },
        { ru: "Молоко", transliteration: "moloko", es: "Leche" },
        { ru: "Кофе", transliteration: "kofe", es: "Café (la bebida)" },
      ],
      fillBlank: {
        title: "Practicá sustantivos: lugares, personas y cosas",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "кофе", transliteration: "kofe" },
          { ru: "книга", transliteration: "kniga" },
          { ru: "друг", transliteration: "drug" },
          { ru: "врач", transliteration: "vrach" },
          { ru: "учитель", transliteration: "uchitel'" },
          { ru: "город", transliteration: "gorod" },
          { ru: "отель", transliteration: "otel'" },
        ],
        sentences: [
          { before: "Я пью ", answer: "кофе", after: ".", es: "Bebo café." },
          { before: "У меня есть ", answer: "книга", after: ".", es: "Tengo un libro." },
          { before: "Он мой ", answer: "друг", after: ".", es: "Él es mi amigo." },
          { before: "Мой брат — ", answer: "врач", after: ".", es: "Mi hermano es médico." },
          { before: "Моя сестра — ", answer: "учитель", after: ".", es: "Mi hermana es maestra." },
          { before: "Это большой ", answer: "город", after: ".", es: "Esta es una ciudad grande." },
          { before: "У нас новый ", answer: "отель", after: ".", es: "Tenemos un hotel nuevo." },
        ],
      },
    },
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Говорить", transliteration: "govorit'", es: "Hablar" },
        { ru: "Пить", transliteration: "pit'", es: "Beber" },
        { ru: "Играть", transliteration: "igrat'", es: "Tocar (música) / Jugar" },
        { ru: "Брать", transliteration: "brat'", es: "Tomar / Llevar" },
        { ru: "Ехать", transliteration: "yekhat'", es: "Ir (en transporte)" },
        { ru: "Жить", transliteration: "zhit'", es: "Vivir" },
        { ru: "Зовут", transliteration: "zovut", es: "(se) llama / llaman" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "говорит", transliteration: "govorit" },
          { ru: "пьёт", transliteration: "p'yot" },
          { ru: "играет", transliteration: "igrayet" },
          { ru: "берёт", transliteration: "beryot" },
          { ru: "живёт", transliteration: "zhivyot" },
        ],
        sentences: [
          { before: "Она ", answer: "говорит", after: " по-русски.", es: "Ella habla en ruso." },
          { before: "Он ", answer: "пьёт", after: " кофе.", es: "Él bebe café." },
          { before: "Друг ", answer: "играет", after: " дома.", es: "El amigo juega en casa." },
          { before: "Студент ", answer: "берёт", after: " кофе.", es: "El estudiante toma un café." },
          { before: "Врач ", answer: "живёт", after: " здесь.", es: "El médico vive aquí." },
        ],
      },
    },
    {
      title: "Adjetivos y posesivos",
      vocabulary: [
        { ru: "Большой", transliteration: "bol'shoy", es: "Grande" },
        { ru: "Новый", transliteration: "novyy", es: "Nuevo" },
        { ru: "Мой", transliteration: "moy", es: "Mi / Mío" },
        { ru: "Твой", transliteration: "tvoy", es: "Tu / Tuyo" },
        { ru: "Красивый", transliteration: "krasivyy", es: "Lindo / Hermoso" },
        { ru: "Старый", transliteration: "staryy", es: "Viejo" },
        { ru: "Хороший", transliteration: "khoroshiy", es: "Bueno (adjetivo)" },
        { ru: "Маленький", transliteration: "malen'kiy", es: "Chico / Pequeño" },
        { ru: "Удобный", transliteration: "udobnyy", es: "Cómodo" },
      ],
      fillBlank: {
        title: "Practicá los adjetivos y posesivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "старый", transliteration: "staryy" },
          { ru: "новый", transliteration: "novyy" },
          { ru: "мой", transliteration: "moy" },
          { ru: "твой", transliteration: "tvoy" },
          { ru: "хороший", transliteration: "khoroshiy" },
          { ru: "удобный", transliteration: "udobnyy" },
        ],
        sentences: [
          { before: "Это ", answer: "старый", after: " дом.", es: "Esta es una casa antigua." },
          { before: "Это ", answer: "новый", after: " телефон.", es: "Este es un teléfono nuevo." },
          { before: "Это ", answer: "мой", after: " друг.", es: "Este es mi amigo." },
          { before: "Это ", answer: "твой", after: " учитель.", es: "Este es tu maestro." },
          { before: "Мой друг очень ", answer: "хороший", after: ".", es: "Mi amigo es muy bueno." },
          { before: "Отель очень ", answer: "удобный", after: ".", es: "El hotel es muy cómodo." },
        ],
      },
    },
    {
      title: "Adverbios y cortesía",
      vocabulary: [
        { ru: "Где", transliteration: "gde", es: "Dónde" },
        { ru: "Здесь", transliteration: "zdes'", es: "Aquí" },
        { ru: "Там", transliteration: "tam", es: "Allá / Ahí" },
        { ru: "Рядом", transliteration: "ryadom", es: "Cerca" },
        { ru: "Дома", transliteration: "doma", es: "En casa" },
        { ru: "Спасибо", transliteration: "spasibo", es: "Gracias" },
        { ru: "Пожалуйста", transliteration: "pozhaluysta", es: "Por favor / De nada" },
        { ru: "Тоже", transliteration: "tozhe", es: "También" },
        { ru: "Сейчас", transliteration: "seychas", es: "Ahora" },
        { ru: "Вечером", transliteration: "vecherom", es: "Por la noche / tarde" },
        { ru: "Спокойно", transliteration: "spokoyno", es: "Tranquilo / Tranquilamente" },
        { ru: "Хорошо", transliteration: "khorosho", es: "Bien" },
      ],
      fillBlank: {
        title: "Practicá los adverbios y las palabras de cortesía",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "где", transliteration: "gde" },
          { ru: "здесь", transliteration: "zdes'" },
          { ru: "там", transliteration: "tam" },
          { ru: "рядом", transliteration: "ryadom" },
          { ru: "дома", transliteration: "doma" },
          { ru: "спасибо", transliteration: "spasibo" },
          { ru: "пожалуйста", transliteration: "pozhaluysta" },
          { ru: "сейчас", transliteration: "seychas" },
        ],
        sentences: [
          { before: "", answer: "где", after: " мой друг?", es: "¿Dónde está mi amigo?" },
          { before: "Книга ", answer: "здесь", after: ".", es: "El libro está aquí." },
          { before: "Врач ", answer: "там", after: ".", es: "El médico está allá." },
          { before: "Отель ", answer: "рядом", after: ".", es: "El hotel está cerca." },
          { before: "Сегодня я ", answer: "дома", after: ".", es: "Hoy estoy en casa." },
          { before: "", answer: "спасибо", after: "!", es: "¡Gracias!" },
          { before: "Спасибо! — ", answer: "пожалуйста", after: ".", es: "¡Gracias! — De nada." },
          { before: "", answer: "сейчас", after: " я дома.", es: "Ahora estoy en casa." },
        ],
      },
    },
  ],
};
