export const lesson = {
  slug: "alphabet",
  level: "A1",
  module: "Módulo 1 — Alfabeto y fonética",
  order: 1,
  title: "El alfabeto y los sonidos rusos",
  alphabet: [
    { letter: "А а", transliteration: "a", type: "Vocal" },
    { letter: "Б б", transliteration: "b", type: "Consonante" },
    { letter: "В в", transliteration: "v", type: "Consonante" },
    { letter: "Г г", transliteration: "g", type: "Consonante" },
    { letter: "Д д", transliteration: "d", type: "Consonante" },
    { letter: "Е е", transliteration: "ye", type: "Vocal" },
    { letter: "Ё ё", transliteration: "yo", type: "Vocal" },
    { letter: "Ж ж", transliteration: "zh", type: "Consonante" },
    { letter: "З з", transliteration: "z", type: "Consonante" },
    { letter: "И и", transliteration: "i", type: "Vocal" },
    { letter: "Й й", transliteration: "y", type: "Semivocal" },
    { letter: "К к", transliteration: "k", type: "Consonante" },
    { letter: "Л л", transliteration: "l", type: "Consonante" },
    { letter: "М м", transliteration: "m", type: "Consonante" },
    { letter: "Н н", transliteration: "n", type: "Consonante" },
    { letter: "О о", transliteration: "o", type: "Vocal" },
    { letter: "П п", transliteration: "p", type: "Consonante" },
    { letter: "Р р", transliteration: "r", type: "Consonante" },
    { letter: "С с", transliteration: "s", type: "Consonante" },
    { letter: "Т т", transliteration: "t", type: "Consonante" },
    { letter: "У у", transliteration: "u", type: "Vocal" },
    { letter: "Ф ф", transliteration: "f", type: "Consonante" },
    { letter: "Х х", transliteration: "kh", type: "Consonante" },
    { letter: "Ц ц", transliteration: "ts", type: "Consonante" },
    { letter: "Ч ч", transliteration: "ch", type: "Consonante" },
    { letter: "Ш ш", transliteration: "sh", type: "Consonante" },
    { letter: "Щ щ", transliteration: "shch", type: "Consonante" },
    { letter: "Ъ ъ", transliteration: "(signo duro)", type: "Signo" },
    { letter: "Ы ы", transliteration: "y", type: "Vocal" },
    { letter: "Ь ь", transliteration: "(signo blando)", type: "Signo" },
    { letter: "Э э", transliteration: "e", type: "Vocal" },
    { letter: "Ю ю", transliteration: "yu", type: "Vocal" },
    { letter: "Я я", transliteration: "ya", type: "Vocal" },
  ],
  vocabulary: [
    { ru: "Метро", transliteration: "metro", es: "Metro" },
    { ru: "Ресторан", transliteration: "restoran", es: "Restaurante" },
    { ru: "Банк", transliteration: "bank", es: "Banco" },
    { ru: "Кафе", transliteration: "kafe", es: "Café (lugar)" },
    { ru: "Телефон", transliteration: "telefon", es: "Teléfono" },
    { ru: "Интернет", transliteration: "internet", es: "Internet" },
    { ru: "Шоколад", transliteration: "shokolad", es: "Chocolate" },
    { ru: "Музыка", transliteration: "muzyka", es: "Música" },
    { ru: "Доктор", transliteration: "doktor", es: "Doctor" },
    { ru: "Такси", transliteration: "taksi", es: "Taxi" },
  ],
  grammarPoint: {
    title: "El acento tónico (ударение) y las consonantes duras/blandas",
    explanation:
      "En ruso el acento tónico no es fijo: cae en una sílaba distinta según la palabra, y hay que aprenderlo con cada vocablo. Una vocal átona cambia de sonido — por ejemplo, la 'о' sin acento suena como 'a'. Además, casi todas las consonantes tienen una versión dura y una blanda, que suaviza el sonido cuando le sigue una vocal como я, е, ё, ю o и, o el signo blando ь.",
    tables: [
      {
        title: "Vocal «о» acentuada vs. átona",
        columns: ["Palabra", "Vocal átona", "Cómo suena"],
        rows: [
          ["Молоко", "las dos «о» iniciales", "malakó (suenan como «a»)"],
          ["Хорошо", "la «о» de la 1ª sílaba", "jarashó (suena como «a»)"],
          ["Москва", "la «о» inicial", "maskvá (suena como «a»)"],
          ["Окно", "la «о» inicial", "aknó (suena como «a»)"],
        ],
        note: "Solo la vocal acentuada conserva su sonido pleno; las «о» átonas casi siempre se reducen a un sonido parecido a «a».",
      },
    ],
    examples: [
      { ru: "Молоко", transliteration: "malako", es: "Leche (las dos 'о' átonas suenan 'a')" },
      { ru: "Хорошо", transliteration: "kharasho", es: "Bien (acento en la última sílaba)" },
      { ru: "Москва", transliteration: "maskva", es: "Moscú (la primera 'о' suena 'a')" },
      { ru: "Мама", transliteration: "mama", es: "Mamá (consonante 'м' dura)" },
    ],
  },
  conversation: {
    title: "🏙️ Preguntando por la calle",
    lines: [
      {
        speaker: "A",
        transliteration: "skazhite, pozhaluysta, gde zdes' metro?",
        segments: [{ ru: "Скажите, пожалуйста, где здесь метро?", es: "Dígame, por favor, ¿dónde está el metro aquí?" }],
      },
      {
        speaker: "B",
        transliteration: "metro ryadom, von tam.",
        segments: [{ ru: "Метро рядом, вон там.", es: "El metro está cerca, allí." }],
      },
      {
        speaker: "A",
        transliteration: "a restoran «Moskva»?",
        segments: [{ ru: "А ресторан «Москва»?", es: "¿Y el restaurante \"Moscú\"?" }],
      },
      {
        speaker: "B",
        transliteration: "restoran tam zhe, ryadom s bankom.",
        segments: [{ ru: "Ресторан там же, рядом с банком.", es: "El restaurante está en el mismo lugar, cerca del banco." }],
      },
      {
        speaker: "A",
        transliteration: "spasibo bol'shoye!",
        segments: [{ ru: "Спасибо большое!", es: "¡Muchas gracias!" }],
      },
    ],
  },
  reading: {
    title: "Una ciudad fácil de leer",
    type: "artículo",
    paragraphs: [
      {
        segments: [
          { ru: "Это большой город.", es: "Esta es una ciudad grande." },
          { ru: "В центре города есть банк, кафе и ресторан.", es: "En el centro de la ciudad hay un banco, un café y un restaurante." },
          { ru: "Рядом станция метро.", es: "Cerca hay una estación de metro." },
        ],
      },
      {
        segments: [
          { ru: "Люди сидят в кафе, пьют кофе и говорят по телефону.", es: "La gente se sienta en el café, toma café y habla por teléfono." },
          { ru: "У них есть интернет, и это удобно.", es: "Tienen internet, y eso es cómodo." },
        ],
      },
      {
        segments: [
          { ru: "Вечером в ресторане играет музыка.", es: "Por la noche, en el restaurante suena música." },
          { ru: "Там едят шоколад и пиццу.", es: "Allí comen chocolate y pizza." },
          { ru: "Потом туристы берут такси и едут в отель.", es: "Luego los turistas toman un taxi y van al hotel." },
        ],
      },
    ],
  },
};
