export const lesson = {
  slug: "a1-vocab-3",
  level: "A1",
  type: "vocabulary",
  module: "Vocabulario 3",
  order: 10,
  title: "Vocabulario 3",
  topics: [
    {
      title: "Números",
      vocabulary: [
        { ru: "Один", transliteration: "odin", es: "Uno" },
        { ru: "Сорок", transliteration: "sorok", es: "Cuarenta" },
        { ru: "Шестьдесят", transliteration: "shest'desyat", es: "Sesenta" },
        { ru: "Семьдесят", transliteration: "sem'desyat", es: "Setenta" },
        { ru: "Восемьдесят", transliteration: "vosem'desyat", es: "Ochenta" },
        { ru: "Девяносто", transliteration: "devyanosto", es: "Noventa" },
      ],
      fillBlank: {
        title: "Practicá los números",
        instructions: "Completá cada cuenta con el número correcto.",
        wordBank: [
          { ru: "сорок", transliteration: "sorok" },
          { ru: "шестьдесят", transliteration: "shest'desyat" },
          { ru: "семьдесят", transliteration: "sem'desyat" },
          { ru: "восемьдесят", transliteration: "vosem'desyat" },
          { ru: "девяносто", transliteration: "devyanosto" },
          { ru: "один", transliteration: "odin" },
        ],
        sentences: [
          { before: "20 + 20 = ", answer: "сорок", after: ".", es: "20 + 20 = cuarenta." },
          { before: "30 + 30 = ", answer: "шестьдесят", after: ".", es: "30 + 30 = sesenta." },
          { before: "30 + 40 = ", answer: "семьдесят", after: ".", es: "30 + 40 = setenta." },
          { before: "40 + 40 = ", answer: "восемьдесят", after: ".", es: "40 + 40 = ochenta." },
          { before: "40 + 50 = ", answer: "девяносто", after: ".", es: "40 + 50 = noventa." },
          { before: "У меня есть ", answer: "один", after: " друг.", es: "Tengo un amigo." },
        ],
      },
    },
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Ходить", transliteration: "khodit'", es: "Ir a pie (habitual)" },
        { ru: "Готовить", transliteration: "gotovit'", es: "Cocinar" },
        { ru: "Собираться", transliteration: "sobirat'sya", es: "Reunirse" },
        { ru: "Взять", transliteration: "vzyat'", es: "Tomar / Llevar (perfectivo)" },
        { ru: "Продавать", transliteration: "prodavat'", es: "Vender" },
        { ru: "Платить", transliteration: "platit'", es: "Pagar" },
        { ru: "Был", transliteration: "byl", es: "Fue / Estaba (pasado de «быть»)" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "ходит", transliteration: "khodit" },
          { ru: "готовит", transliteration: "gotovit" },
          { ru: "собирается", transliteration: "sobirayetsya" },
          { ru: "возьмёт", transliteration: "voz'myot" },
          { ru: "продаёт", transliteration: "prodayot" },
          { ru: "платит", transliteration: "platit" },
          { ru: "был", transliteration: "byl" },
        ],
        sentences: [
          { before: "Друг ", answer: "ходит", after: " в город.", es: "El amigo va a la ciudad (a pie, habitual)." },
          { before: "Она ", answer: "готовит", after: " дома.", es: "Ella cocina en casa." },
          { before: "Она ", answer: "собирается", after: ".", es: "Ella se está preparando." },
          { before: "Он ", answer: "возьмёт", after: " хлеб.", es: "Él tomará pan." },
          { before: "Продавец ", answer: "продаёт", after: " хлеб.", es: "El vendedor vende pan." },
          { before: "Турист ", answer: "платит", after: " рубль.", es: "El turista paga un rublo." },
          { before: "Вчера он ", answer: "был", after: " дома.", es: "Ayer él estuvo en casa." },
        ],
      },
    },
    {
      title: "Sustantivos",
      vocabulary: [
        { ru: "Год", transliteration: "god", es: "Año" },
        { ru: "Подруга", transliteration: "podruga", es: "Amiga" },
        { ru: "Банан", transliteration: "banan", es: "Plátano / Banana" },
        { ru: "Продавец", transliteration: "prodavets", es: "Vendedor" },
      ],
      fillBlank: {
        title: "Practicá los sustantivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "год", transliteration: "god" },
          { ru: "подруга", transliteration: "podruga" },
          { ru: "банан", transliteration: "banan" },
          { ru: "продавец", transliteration: "prodavets" },
        ],
        sentences: [
          { before: "Это был хороший ", answer: "год", after: ".", es: "Fue un buen año." },
          { before: "Это была моя ", answer: "подруга", after: ".", es: "Esa era mi amiga." },
          { before: "Я ем ", answer: "банан", after: ".", es: "Como una banana." },
          { before: "На рынке работает ", answer: "продавец", after: ".", es: "En el mercado trabaja un vendedor." },
        ],
      },
    },
    {
      title: "Adjetivos",
      vocabulary: [
        { ru: "Вкусный", transliteration: "vkusnyy", es: "Rico / Delicioso" },
        { ru: "Обычный", transliteration: "obychnyy", es: "Normal / Corriente" },
        { ru: "Дружный", transliteration: "druzhnyy", es: "Unido (familia)" },
        { ru: "Уютный", transliteration: "uyutnyy", es: "Acogedor" },
        { ru: "Весь", transliteration: "ves'", es: "Todo / Toda" },
        { ru: "Свой", transliteration: "svoy", es: "Propio (posesivo reflexivo)" },
      ],
      fillBlank: {
        title: "Practicá los adjetivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "вкусный", transliteration: "vkusnyy" },
          { ru: "обычный", transliteration: "obychnyy" },
          { ru: "уютный", transliteration: "uyutnyy" },
          { ru: "весь", transliteration: "ves'" },
          { ru: "свой", transliteration: "svoy" },
        ],
        sentences: [
          { before: "Это очень ", answer: "вкусный", after: " хлеб.", es: "Este pan es muy rico." },
          { before: "Это мой ", answer: "обычный", after: " день.", es: "Este es mi día normal." },
          { before: "Это ", answer: "уютный", after: " кафе.", es: "Este es un café acogedor." },
          { before: "Это ", answer: "весь", after: " день.", es: "Este es todo el día." },
          { before: "Это ", answer: "свой", after: " друг.", es: "Este es su propio amigo." },
        ],
      },
    },
    {
      title: "Adverbios y otras palabras útiles",
      vocabulary: [
        { ru: "Откуда", transliteration: "otkuda", es: "De dónde" },
        { ru: "Вчера", transliteration: "vchera", es: "Ayer" },
        { ru: "По-русски", transliteration: "po-russki", es: "En ruso" },
        { ru: "Нет", transliteration: "nyet", es: "No hay / No (negación)" },
        { ru: "Только", transliteration: "tol'ko", es: "Solo / Únicamente" },
        { ru: "Понятно", transliteration: "ponyatno", es: "Entendido" },
        { ru: "Часто", transliteration: "chasto", es: "A menudo" },
        { ru: "Очень", transliteration: "ochen'", es: "Muy" },
        { ru: "Вместе", transliteration: "vmeste", es: "Juntos" },
      ],
      fillBlank: {
        title: "Practicá los adverbios y palabras útiles",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "откуда", transliteration: "otkuda" },
          { ru: "вчера", transliteration: "vchera" },
          { ru: "по-русски", transliteration: "po-russki" },
          { ru: "нет", transliteration: "nyet" },
          { ru: "только", transliteration: "tol'ko" },
          { ru: "понятно", transliteration: "ponyatno" },
          { ru: "часто", transliteration: "chasto" },
          { ru: "очень", transliteration: "ochen'" },
          { ru: "вместе", transliteration: "vmeste" },
        ],
        sentences: [
          { before: "", answer: "откуда", after: " ты?", es: "¿De dónde sos?" },
          { before: "", answer: "вчера", after: " я был дома.", es: "Ayer estuve en casa." },
          { before: "Мы говорим ", answer: "по-русски", after: ".", es: "Hablamos en ruso." },
          { before: "Ты дома? — ", answer: "нет", after: ".", es: "¿Estás en casa? — No." },
          { before: "Я ", answer: "только", after: " студент.", es: "Soy solo estudiante." },
          { before: "", answer: "понятно", after: ".", es: "Entendido." },
          { before: "Я ", answer: "часто", after: " пью чай.", es: "Tomo té a menudo." },
          { before: "Это ", answer: "очень", after: " хорошо.", es: "Esto está muy bien." },
          { before: "Мы гуляем ", answer: "вместе", after: ".", es: "Paseamos juntos." },
        ],
      },
    },
  ],
};
