export const lesson = {
  slug: "gender-number",
  level: "A1",
  module: "Módulo 3 — Género y plural de sustantivos",
  order: 4,
  title: "Género y plural de sustantivos",
  vocabulary: [
    { ru: "Стол", transliteration: "stol", es: "Mesa (masculino)" },
    { ru: "Дом", transliteration: "dom", es: "Casa (masculino)" },
    { ru: "Студент", transliteration: "student", es: "Estudiante (masculino)" },
    { ru: "Друг", transliteration: "drug", es: "Amigo (masculino)" },
    { ru: "Книга", transliteration: "kniga", es: "Libro (femenino)" },
    { ru: "Машина", transliteration: "mashina", es: "Auto (femenino)" },
    { ru: "Комната", transliteration: "komnata", es: "Habitación (femenino)" },
    { ru: "Окно", transliteration: "okno", es: "Ventana (neutro)" },
    { ru: "Письмо", transliteration: "pis'mo", es: "Carta (neutro)" },
    { ru: "Море", transliteration: "morye", es: "Mar (neutro)" },
    { ru: "Язык", transliteration: "yazyk", es: "Idioma / lengua (masculino)" },
    { ru: "Урок", transliteration: "urok", es: "Lección (masculino)" },
    { ru: "Карандаш", transliteration: "karandash", es: "Lápiz (masculino)" },
    { ru: "Подруга", transliteration: "podruga", es: "Amiga (femenino)" },
    { ru: "Город", transliteration: "gorod", es: "Ciudad (masculino, plural irregular)" },
    { ru: "Вечер", transliteration: "vecher", es: "Tarde/noche (masculino, plural irregular)" },
    { ru: "Учитель", transliteration: "uchitel'", es: "Profesor (masculino, plural irregular)" },
    { ru: "Глаз", transliteration: "glaz", es: "Ojo (masculino, plural irregular)" },
    { ru: "Брат", transliteration: "brat", es: "Hermano (plural totalmente irregular)" },
    { ru: "Стул", transliteration: "stul", es: "Silla (plural totalmente irregular)" },
    { ru: "Дерево", transliteration: "derevo", es: "Árbol (plural totalmente irregular)" },
    { ru: "Ребёнок", transliteration: "rebyonok", es: "Niño (plural totalmente irregular)" },
    { ru: "Человек", transliteration: "chelovek", es: "Persona (plural totalmente irregular)" },
  ],
  grammarPoint: {
    title: "Género y plural de sustantivos",
    explanation:
      "Los sustantivos rusos tienen tres géneros que se reconocen por su terminación: masculino (consonante), femenino (-а/-я) y neutro (-о/-е). El plural regular se forma cambiando la terminación: masculino y femenino añaden -ы/-и, y el neutro cambia a -а/-я. Además hay una regla ortográfica que reemplaza -ы por -и después de ciertas consonantes, y un puñado de plurales totalmente irregulares que hay que memorizar.",
    tables: [
      {
        title: "Género y plural de sustantivos",
        columns: ["Género", "Terminación singular", "Regla", "Ejemplo"],
        rows: [
          ["Masculino", "consonante", "Añade -ы", "студент (estudiante) → студенты"],
          ["Masculino", "-й / -ь", "Cambia por -и", "музей (museo) → музеи"],
          ["Masculino", "г, к, х, ж, ч, ш, щ + ы", "Regla ortográfica: nunca -ы, usa -и", "стол (mesa) → столы, pero язык (idioma) → языки"],
          ["Femenino", "-а", "Cambia por -ы (o por -и tras г, к, х, ж, ч, ш, щ)", "газета (periódico) → газеты; книга (libro) → книги"],
          ["Femenino", "-я", "Cambia por -и", "станция (estación) → станции"],
          ["Femenino", "-ь", "Cambia por -и", "дверь (puerta) → двери"],
          ["Neutro", "-о", "Cambia por -а", "окно (ventana) → окна"],
          ["Neutro", "-е", "Cambia por -я", "здание (edificio) → здания"],
        ],
        note: "Estas son las terminaciones regulares; algunos sustantivos frecuentes forman el plural de manera irregular (ver tablas siguientes).",
      },
      {
        title: "Regla ortográfica: nunca -ы después de г, к, х, ж, ч, ш, щ",
        columns: ["Singular", "Plural esperado", "Plural real"],
        rows: [
          ["язык (idioma)", "языкы ✗", "языки"],
          ["урок (lección)", "урокы ✗", "уроки"],
          ["карандаш (lápiz)", "карандашы ✗", "карандаши"],
          ["книга (libro)", "книгы ✗", "книги"],
          ["рука (mano)", "рукы ✗", "руки"],
          ["подруга (amiga)", "подругы ✗", "подруги"],
        ],
        note: "Después de las siete letras г, к, х, ж, ч, ш, щ nunca se escribe -ы: se escribe -и en su lugar. Por eso книга hace книги y no книгы, y карандаш hace карандаши y no карандашы.",
      },
      {
        title: "Plurales totalmente irregulares",
        columns: ["Singular", "Plural", "Significado"],
        rows: [
          ["друг", "друзья", "amigo / amigos"],
          ["брат", "братья", "hermano / hermanos"],
          ["стул", "стулья", "silla / sillas"],
          ["лист", "листья", "hoja / hojas"],
          ["сын", "сыновья", "hijo / hijos"],
          ["дерево", "деревья", "árbol / árboles"],
          ["ребёнок", "дети", "niño / niños"],
          ["человек", "люди", "persona / personas"],
        ],
        note: "Estos plurales no derivan de ninguna regla de terminación: cambian de raíz o toman un sufijo especial (-ья). Son palabras de uso muy frecuente, así que conviene memorizar el par singular-plural como si fuera una palabra nueva.",
      },
    ],
    examples: [
      { ru: "Друг → Друзья", transliteration: "drug → druz'ya", es: "Amigo → Amigos (plural irregular)" },
      { ru: "Учитель → Учителя", transliteration: "uchitel' → uchitelya", es: "Profesor → Profesores (plural en -я)" },
      { ru: "Город → Города", transliteration: "gorod → goroda", es: "Ciudad → Ciudades (plural en -а)" },
      { ru: "Книга → Книги", transliteration: "kniga → knigi", es: "Libro → Libros (regla ortográfica)" },
    ],
  },
  conversation: {
    title: "🏠 Describiendo la casa",
    lines: [
      {
        speaker: "A",
        transliteration: "eto tvoy dom?",
        segments: [{ ru: "Это твой дом?", es: "¿Esta es tu casa?" }],
      },
      {
        speaker: "B",
        transliteration: "da, eto moy novyy dom. on bol'shoy.",
        segments: [
          { ru: "Да, это мой новый дом.", es: "Sí, esta es mi casa nueva." },
          { ru: "Он большой.", es: "Es grande." },
        ],
      },
      {
        speaker: "A",
        transliteration: "a eto tvoya mashina?",
        segments: [{ ru: "А это твоя машина?", es: "¿Y este es tu auto?" }],
      },
      {
        speaker: "B",
        transliteration: "da, mashina tozhe novaya.",
        segments: [{ ru: "Да, машина тоже новая.", es: "Sí, el auto también es nuevo." }],
      },
      {
        speaker: "A",
        transliteration: "u vas krasivyye okna!",
        segments: [{ ru: "У вас красивые окна!", es: "¡Tienen ventanas hermosas!" }],
      },
    ],
  },
  reading: {
    title: "La casa de Iván",
    type: "historia",
    paragraphs: [
      {
        segments: [
          { ru: "У Ивана есть большой дом.", es: "Iván tiene una casa grande." },
          { ru: "В доме есть новая кухня и красивая комната.", es: "En la casa hay una cocina nueva y una habitación bonita." },
          { ru: "Окна в доме большие и светлые.", es: "Las ventanas de la casa son grandes y luminosas." },
        ],
      },
      {
        segments: [
          { ru: "У Ивана есть старый друг, его зовут Пётр.", es: "Iván tiene un viejo amigo, se llama Piotr." },
          { ru: "Пётр — хороший студент.", es: "Piotr es un buen estudiante." },
          { ru: "У него есть маленькая машина и старая книга.", es: "Él tiene un auto pequeño y un libro viejo." },
        ],
      },
      {
        segments: [
          { ru: "Дома у Ивана и Петра разные, но оба дома удобные.", es: "Las casas de Iván y Piotr son diferentes, pero ambas casas son cómodas." },
        ],
      },
    ],
  },
  fillBlank: {
    title: "Practicá el género y el plural de los sustantivos",
    instructions: "Completá cada frase con la palabra correcta, o su plural.",
    wordBank: [
      { ru: "машина", transliteration: "mashina" },
      { ru: "окно", transliteration: "okno" },
      { ru: "книга", transliteration: "kniga" },
      { ru: "письмо", transliteration: "pis'mo" },
      { ru: "языки", transliteration: "yazyki" },
      { ru: "карандаши", transliteration: "karandashi" },
      { ru: "дома", transliteration: "doma" },
      { ru: "города", transliteration: "goroda" },
      { ru: "учителя", transliteration: "uchitelya" },
      { ru: "друзья", transliteration: "druz'ya" },
      { ru: "стулья", transliteration: "stul'ya" },
      { ru: "дети", transliteration: "deti" },
    ],
    sentences: [
      { before: "Что это? 🚗 — ", answer: "машина", after: ".", es: "¿Qué es esto? 🚗 — un auto." },
      { before: "Что это? 🪟 — ", answer: "окно", after: ".", es: "¿Qué es esto? 🪟 — una ventana." },
      { before: "Что это? 📖 — ", answer: "книга", after: ".", es: "¿Qué es esto? 📖 — un libro." },
      { before: "Что это? ✉️ — ", answer: "письмо", after: ".", es: "¿Qué es esto? ✉️ — una carta." },
      { before: "Здесь мои ", answer: "языки", after: ".", es: "Aquí están mis idiomas. (язык, regla ortográfica -и)" },
      { before: "На столе лежат ", answer: "карандаши", after: ".", es: "Sobre la mesa hay lápices. (карандаш, regla ortográfica -и)" },
      { before: "Это наши новые ", answer: "дома", after: ".", es: "Estas son nuestras casas nuevas. (дом, plural en -а)" },
      { before: "В России есть красивые ", answer: "города", after: ".", es: "En Rusia hay ciudades hermosas. (город, plural en -а)" },
      { before: "Наши ", answer: "учителя", after: " очень хорошие.", es: "Nuestros profesores son muy buenos. (учитель, plural en -я)" },
      { before: "Мои ", answer: "друзья", after: " живут здесь.", es: "Mis amigos viven aquí. (друг, plural irregular)" },
      { before: "В комнате новые ", answer: "стулья", after: ".", es: "En la habitación hay sillas nuevas. (стул, plural irregular)" },
      { before: "Это наши ", answer: "дети", after: ".", es: "Estos son nuestros niños. (ребёнок, plural irregular)" },
    ],
  },
};
