export const lesson = {
  slug: "b1-vocab-2",
  level: "B1",
  type: "vocabulary",
  module: "Vocabulario 2",
  order: 7,
  title: "Vocabulario 2",
  topics: [
    {
      title: "Sustantivos",
      vocabulary: [
        { ru: "Слово", transliteration: "slovo", es: "Palabra" },
        { ru: "Тема", transliteration: "tema", es: "Tema" },
        { ru: "Вопрос", transliteration: "vopros", es: "Pregunta / cuestión" },
        { ru: "Поезд", transliteration: "poyezd", es: "Tren" },
        { ru: "Идея", transliteration: "ideya", es: "Idea" },
      ],
      fillBlank: {
        title: "Practicá los sustantivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "слово", transliteration: "slovo" },
          { ru: "тема", transliteration: "tema" },
          { ru: "вопрос", transliteration: "vopros" },
          { ru: "поезд", transliteration: "poyezd" },
          { ru: "идея", transliteration: "ideya" },
        ],
        sentences: [
          { before: "Я не знаю это ", answer: "слово", after: ".", es: "No conozco esa palabra." },
          { before: "Это интересная ", answer: "тема", after: ".", es: "Este es un tema interesante." },
          { before: "У меня есть ", answer: "вопрос", after: ".", es: "Tengo una pregunta." },
          { before: "", answer: "поезд", after: " уходит через час.", es: "El tren sale en una hora." },
          { before: "Это хорошая ", answer: "идея", after: ".", es: "Esta es una buena idea." },
        ],
      },
    },
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Чувствовать", transliteration: "chuvstvovat'", es: "Sentir" },
        { ru: "Зависеть", transliteration: "zaviset'", es: "Depender" },
        { ru: "Стать", transliteration: "stat'", es: "Llegar a ser (perfectivo)" },
        { ru: "Казаться", transliteration: "kazat'sya", es: "Parecer" },
        { ru: "Слышать", transliteration: "slyshat'", es: "Oír" },
        { ru: "Слушать", transliteration: "slushat'", es: "Escuchar" },
        { ru: "Искать", transliteration: "iskat'", es: "Buscar" },
        { ru: "Уметь", transliteration: "umet'", es: "Saber hacer algo" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "чувствует", transliteration: "chuvstvuyet" },
          { ru: "зависит", transliteration: "zavisit" },
          { ru: "станет", transliteration: "stanet" },
          { ru: "кажется", transliteration: "kazhetsya" },
          { ru: "слышит", transliteration: "slyshit" },
          { ru: "слушает", transliteration: "slushayet" },
          { ru: "ищет", transliteration: "ishchet" },
          { ru: "умеет", transliteration: "umeyet" },
        ],
        sentences: [
          { before: "Она себя хорошо ", answer: "чувствует", after: ".", es: "Ella se siente bien." },
          { before: "Это ", answer: "зависит", after: " от тебя.", es: "Esto depende de ti." },
          { before: "Он ", answer: "станет", after: " врачом.", es: "Él será médico." },
          { before: "Мне ", answer: "кажется", after: ", что это правда.", es: "Me parece que es verdad." },
          { before: "Она хорошо ", answer: "слышит", after: ".", es: "Ella oye bien." },
          { before: "Он ", answer: "слушает", after: " музыку.", es: "Él escucha música." },
          { before: "Она ", answer: "ищет", after: " книгу.", es: "Ella busca un libro." },
          { before: "Он не ", answer: "умеет", after: " плавать.", es: "Él no sabe nadar." },
        ],
      },
    },
    {
      title: "Adjetivos",
      vocabulary: [
        { ru: "Простой", transliteration: "prostoy", es: "Simple" },
        { ru: "Разный", transliteration: "raznyy", es: "Diferente" },
        { ru: "Готовый", transliteration: "gotovyy", es: "Listo" },
      ],
      fillBlank: {
        title: "Practicá los adjetivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "простой", transliteration: "prostoy" },
          { ru: "разный", transliteration: "raznyy" },
          { ru: "готовый", transliteration: "gotovyy" },
        ],
        sentences: [
          { before: "Это ", answer: "простой", after: " вопрос.", es: "Esta es una pregunta simple." },
          { before: "Это совсем ", answer: "разный", after: " вопрос.", es: "Esta es una pregunta completamente distinta." },
          { before: "Это ", answer: "готовый", after: " ужин.", es: "Esta es una cena lista." },
        ],
      },
    },
    {
      title: "Adverbios y otras palabras útiles",
      vocabulary: [
        { ru: "Нужно", transliteration: "nuzhno", es: "Hace falta" },
        { ru: "Через", transliteration: "cherez", es: "A través de / dentro de (tiempo)" },
        { ru: "Почему", transliteration: "pochemu", es: "Por qué" },
        { ru: "Иногда", transliteration: "inogda", es: "A veces" },
        { ru: "Именно", transliteration: "imenno", es: "Precisamente" },
      ],
      fillBlank: {
        title: "Practicá los adverbios y palabras útiles",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "нужно", transliteration: "nuzhno" },
          { ru: "через", transliteration: "cherez" },
          { ru: "почему", transliteration: "pochemu" },
          { ru: "иногда", transliteration: "inogda" },
          { ru: "именно", transliteration: "imenno" },
        ],
        sentences: [
          { before: "Мне ", answer: "нужно", after: " помочь тебе.", es: "Necesito ayudarte." },
          { before: "Он придёт ", answer: "через", after: " час.", es: "Él vendrá en una hora." },
          { before: "", answer: "почему", after: " ты не пришёл?", es: "¿Por qué no viniste?" },
          { before: "Я ", answer: "иногда", after: " читаю книги.", es: "A veces leo libros." },
          { before: "Это ", answer: "именно", after: " то, что нужно.", es: "Esto es precisamente lo que hace falta." },
        ],
      },
    },
  ],
};
