export const lesson = {
  slug: "a2-vocab-2",
  level: "A2",
  type: "vocabulary",
  module: "Vocabulario 2",
  order: 7,
  title: "Vocabulario 2",
  topics: [
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Знать", transliteration: "znat'", es: "Saber / conocer" },
        { ru: "Бояться", transliteration: "boyat'sya", es: "Temer" },
        { ru: "Мечтать", transliteration: "mechtat'", es: "Soñar" },
        { ru: "Пройти", transliteration: "proyti", es: "Pasar / resultar (perfectivo)" },
        { ru: "Помочь", transliteration: "pomoch'", es: "Ayudar" },
        { ru: "Подумать", transliteration: "podumat'", es: "Pensar (perfectivo)" },
        { ru: "Хватить", transliteration: "khvatit'", es: "Alcanzar / bastar" },
        { ru: "Думать", transliteration: "dumat'", es: "Pensar" },
        { ru: "Открыть", transliteration: "otkryt'", es: "Abrir" },
        { ru: "Верить", transliteration: "verit'", es: "Creer" },
        { ru: "Приходить", transliteration: "prikhodit'", es: "Venir" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "знает", transliteration: "znayet" },
          { ru: "боится", transliteration: "boitsya" },
          { ru: "мечтает", transliteration: "mechtayet" },
          { ru: "пройдёт", transliteration: "proydyot" },
          { ru: "поможет", transliteration: "pomozhet" },
          { ru: "подумает", transliteration: "podumayet" },
          { ru: "хватит", transliteration: "khvatit" },
          { ru: "думает", transliteration: "dumayet" },
          { ru: "откроет", transliteration: "otkroyet" },
          { ru: "верит", transliteration: "verit" },
          { ru: "приходит", transliteration: "prikhodit" },
        ],
        sentences: [
          { before: "Она ", answer: "знает", after: " русский язык.", es: "Ella sabe ruso." },
          { before: "Он ", answer: "боится", after: ".", es: "Él tiene miedo." },
          { before: "Она часто ", answer: "мечтает", after: ".", es: "Ella sueña a menudo." },
          { before: "День ", answer: "пройдёт", after: " хорошо.", es: "El día pasará bien." },
          { before: "Друг ", answer: "поможет", after: " мне.", es: "El amigo me ayudará." },
          { before: "Она ", answer: "подумает", after: " хорошо.", es: "Ella lo pensará bien." },
          { before: "У меня не ", answer: "хватит", after: " денег.", es: "No me alcanzará el dinero." },
          { before: "Она много ", answer: "думает", after: ".", es: "Ella piensa mucho." },
          { before: "Он ", answer: "откроет", after: " окно.", es: "Él abrirá la ventana." },
          { before: "Она ", answer: "верит", after: " мне.", es: "Ella me cree." },
          { before: "Он ", answer: "приходит", after: " домой поздно.", es: "Él llega a casa tarde." },
        ],
      },
    },
    {
      title: "Sustantivos",
      vocabulary: [
        { ru: "Человек", transliteration: "chelovek", es: "Persona" },
        { ru: "Деревня", transliteration: "derevnya", es: "Pueblo / aldea" },
        { ru: "Свобода", transliteration: "svoboda", es: "Libertad" },
        { ru: "Приключение", transliteration: "priklyucheniye", es: "Aventura" },
        { ru: "Проблема", transliteration: "problema", es: "Problema" },
        { ru: "Деньги", transliteration: "den'gi", es: "Dinero" },
        { ru: "Место", transliteration: "myesto", es: "Lugar" },
      ],
      fillBlank: {
        title: "Practicá los sustantivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "человек", transliteration: "chelovek" },
          { ru: "деревня", transliteration: "derevnya" },
          { ru: "свобода", transliteration: "svoboda" },
          { ru: "приключение", transliteration: "priklyucheniye" },
          { ru: "проблема", transliteration: "problema" },
          { ru: "деньги", transliteration: "den'gi" },
          { ru: "место", transliteration: "myesto" },
        ],
        sentences: [
          { before: "Он очень хороший ", answer: "человек", after: ".", es: "Él es una muy buena persona." },
          { before: "Это тихая ", answer: "деревня", after: ".", es: "Este es un pueblo tranquilo." },
          { before: "Это настоящая ", answer: "свобода", after: ".", es: "Esta es verdadera libertad." },
          { before: "Это было настоящее ", answer: "приключение", after: "!", es: "¡Eso fue una verdadera aventura!" },
          { before: "У нас большая ", answer: "проблема", after: ".", es: "Tenemos un gran problema." },
          { before: "Мне нужны ", answer: "деньги", after: ".", es: "Necesito dinero." },
          { before: "Это хорошее ", answer: "место", after: " для кафе.", es: "Este es un buen lugar para un café." },
        ],
      },
    },
    {
      title: "Adjetivos",
      vocabulary: [
        { ru: "Счастливый", transliteration: "schastlivyy", es: "Feliz" },
        { ru: "Чистый", transliteration: "chistyy", es: "Limpio" },
        { ru: "Энергичный", transliteration: "energichnyy", es: "Enérgico" },
        { ru: "Важный", transliteration: "vazhnyy", es: "Importante" },
        { ru: "Трудный", transliteration: "trudnyy", es: "Difícil" },
        { ru: "Отличный", transliteration: "otlichnyy", es: "Excelente" },
      ],
      fillBlank: {
        title: "Practicá los adjetivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "счастливый", transliteration: "schastlivyy" },
          { ru: "чистый", transliteration: "chistyy" },
          { ru: "энергичный", transliteration: "energichnyy" },
          { ru: "важный", transliteration: "vazhnyy" },
          { ru: "трудный", transliteration: "trudnyy" },
          { ru: "отличный", transliteration: "otlichnyy" },
        ],
        sentences: [
          { before: "Сегодня я очень ", answer: "счастливый", after: ".", es: "Hoy estoy muy feliz." },
          { before: "Это очень ", answer: "чистый", after: " дом.", es: "Esta es una casa muy limpia." },
          { before: "Мой друг очень ", answer: "энергичный", after: ".", es: "Mi amigo es muy enérgico." },
          { before: "Это ", answer: "важный", after: " вопрос.", es: "Este es un asunto importante." },
          { before: "Этот текст очень ", answer: "трудный", after: ".", es: "Este texto es muy difícil." },
          { before: "У нас ", answer: "отличный", after: " ужин.", es: "Tenemos una cena excelente." },
        ],
      },
    },
    {
      title: "Adverbios y comparativos",
      vocabulary: [
        { ru: "Лучше", transliteration: "luchshe", es: "Mejor" },
        { ru: "Самый", transliteration: "samyy", es: "El más / la más" },
        { ru: "Который", transliteration: "kotoryy", es: "Que / el cual" },
        { ru: "Больше", transliteration: "bol'she", es: "Más" },
        { ru: "Домой", transliteration: "domoy", es: "A casa (dirección)" },
        { ru: "Теперь", transliteration: "teper'", es: "Ahora" },
        { ru: "Ещё", transliteration: "yeshcho", es: "Aún / todavía / más" },
      ],
      fillBlank: {
        title: "Practicá los adverbios y comparativos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "лучше", transliteration: "luchshe" },
          { ru: "самый", transliteration: "samyy" },
          { ru: "который", transliteration: "kotoryy" },
          { ru: "больше", transliteration: "bol'she" },
          { ru: "домой", transliteration: "domoy" },
          { ru: "теперь", transliteration: "teper'" },
          { ru: "ещё", transliteration: "yeshcho" },
        ],
        sentences: [
          { before: "Это ", answer: "лучше", after: ", чем я думал.", es: "Esto es mejor de lo que pensaba." },
          { before: "Это ", answer: "самый", after: " интересный фильм.", es: "Esta es la película más interesante." },
          { before: "Это человек, ", answer: "который", after: " живёт здесь.", es: "Esta es la persona que vive aquí." },
          { before: "Я хочу ", answer: "больше", after: " денег.", es: "Quiero más dinero." },
          { before: "Он идёт ", answer: "домой", after: ".", es: "Él va a casa." },
          { before: "", answer: "теперь", after: " всё хорошо.", es: "Ahora todo está bien." },
          { before: "Я хочу ", answer: "ещё", after: " читать.", es: "Quiero seguir leyendo." },
        ],
      },
    },
  ],
};
