export const lesson = {
  slug: "a2-vocab-1",
  level: "A2",
  type: "vocabulary",
  module: "Vocabulario 1",
  order: 1,
  title: "Vocabulario 1",
  topics: [
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Читать", transliteration: "chitat'", es: "Leer" },
        { ru: "Купить", transliteration: "kupit'", es: "Comprar (perfectivo)" },
        { ru: "Вернуться", transliteration: "vernut'sya", es: "Volver / regresar" },
        { ru: "Поехать", transliteration: "poyekhat'", es: "Ir (en transporte, perfectivo)" },
        { ru: "Хотеть", transliteration: "khotet'", es: "Querer" },
        { ru: "Начать", transliteration: "nachat'", es: "Empezar" },
        { ru: "Решить", transliteration: "reshit'", es: "Decidir" },
        { ru: "Найти", transliteration: "nayti", es: "Encontrar" },
        { ru: "Оказаться", transliteration: "okazat'sya", es: "Resultar (ser)" },
        { ru: "Закончить", transliteration: "zakonchit'", es: "Terminar" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "читает", transliteration: "chitayet" },
          { ru: "купит", transliteration: "kupit" },
          { ru: "вернётся", transliteration: "vernyotsya" },
          { ru: "поедет", transliteration: "poyedet" },
          { ru: "хочет", transliteration: "khochet" },
          { ru: "начнёт", transliteration: "nachnyot" },
          { ru: "решит", transliteration: "reshit" },
          { ru: "найдёт", transliteration: "naydyot" },
          { ru: "окажется", transliteration: "okazhetsya" },
          { ru: "закончит", transliteration: "zakonchit" },
        ],
        sentences: [
          { before: "Она ", answer: "читает", after: " роман.", es: "Ella lee una novela." },
          { before: "Он ", answer: "купит", after: " дом.", es: "Él comprará una casa." },
          { before: "Она ", answer: "вернётся", after: " утром.", es: "Ella volverá por la mañana." },
          { before: "Она ", answer: "поедет", after: " в Париж.", es: "Ella irá a París." },
          { before: "Он ", answer: "хочет", after: " читать.", es: "Él quiere leer." },
          { before: "Она ", answer: "начнёт", after: " читать.", es: "Ella empezará a leer." },
          { before: "Она ", answer: "решит", after: " поехать.", es: "Ella decidirá ir." },
          { before: "Он ", answer: "найдёт", after: " план.", es: "Él encontrará un plan." },
          { before: "Всё ", answer: "окажется", after: " хорошо.", es: "Todo resultará bien." },
          { before: "Она ", answer: "закончит", after: " фильм быстро.", es: "Ella terminará la película rápido." },
        ],
      },
    },
    {
      title: "Sustantivos",
      vocabulary: [
        { ru: "Кино", transliteration: "kino", es: "Cine" },
        { ru: "Куртка", transliteration: "kurtka", es: "Chaqueta / campera" },
        { ru: "Фильм", transliteration: "fil'm", es: "Película" },
        { ru: "Отпуск", transliteration: "otpusk", es: "Vacaciones" },
        { ru: "Гостиница", transliteration: "gostinitsa", es: "Hotel" },
        { ru: "Самолёт", transliteration: "samolyot", es: "Avión" },
        { ru: "Музей", transliteration: "muzey", es: "Museo" },
        { ru: "Путешествие", transliteration: "puteshestviye", es: "Viaje" },
        { ru: "Жизнь", transliteration: "zhizn'", es: "Vida" },
        { ru: "План", transliteration: "plan", es: "Plan" },
        { ru: "Лето", transliteration: "leto", es: "Verano" },
        { ru: "Роман", transliteration: "roman", es: "Novela" },
        { ru: "Библиотека", transliteration: "biblioteka", es: "Biblioteca" },
        { ru: "История", transliteration: "istoriya", es: "Historia / relato" },
      ],
      fillBlank: {
        title: "Practicá los sustantivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "фильм", transliteration: "fil'm" },
          { ru: "кино", transliteration: "kino" },
          { ru: "отпуск", transliteration: "otpusk" },
          { ru: "музей", transliteration: "muzey" },
          { ru: "план", transliteration: "plan" },
          { ru: "лето", transliteration: "leto" },
          { ru: "роман", transliteration: "roman" },
          { ru: "библиотека", transliteration: "biblioteka" },
          { ru: "история", transliteration: "istoriya" },
          { ru: "куртка", transliteration: "kurtka" },
          { ru: "гостиница", transliteration: "gostinitsa" },
          { ru: "самолёт", transliteration: "samolyot" },
          { ru: "путешествие", transliteration: "puteshestviye" },
          { ru: "жизнь", transliteration: "zhizn'" },
        ],
        sentences: [
          { before: "Я хочу посмотреть новый ", answer: "фильм", after: ".", es: "Quiero ver una nueva película." },
          { before: "Вечером мы идём в ", answer: "кино", after: ".", es: "Por la noche vamos al cine." },
          { before: "Летом у меня будет ", answer: "отпуск", after: ".", es: "En verano tendré vacaciones." },
          { before: "В центре города есть ", answer: "музей", after: ".", es: "En el centro de la ciudad hay un museo." },
          { before: "У меня есть ", answer: "план", after: " на завтра.", es: "Tengo un plan para mañana." },
          { before: "Моё любимое время года — ", answer: "лето", after: ".", es: "Mi estación favorita es el verano." },
          { before: "Я читаю интересный ", answer: "роман", after: ".", es: "Leo una novela interesante." },
          { before: "В городе есть новая ", answer: "библиотека", after: ".", es: "En la ciudad hay una nueva biblioteca." },
          { before: "Это очень интересная ", answer: "история", after: ".", es: "Esta es una historia muy interesante." },
          { before: "Это моя новая ", answer: "куртка", after: ".", es: "Esta es mi chaqueta nueva." },
          { before: "Это большая ", answer: "гостиница", after: ".", es: "Este es un hotel grande." },
          { before: "", answer: "самолёт", after: " летит быстро.", es: "El avión vuela rápido." },
          { before: "Это моё ", answer: "путешествие", after: ".", es: "Este es mi viaje." },
          { before: "", answer: "жизнь", after: " очень интересная.", es: "La vida es muy interesante." },
        ],
      },
    },
    {
      title: "Adjetivos y conectores",
      vocabulary: [
        { ru: "Молодой", transliteration: "molodoy", es: "Joven" },
        { ru: "Интересный", transliteration: "interesnyy", es: "Interesante" },
        { ru: "Уже", transliteration: "uzhe", es: "Ya" },
        { ru: "Можно", transliteration: "mozhno", es: "Se puede" },
        { ru: "Конечно", transliteration: "konechno", es: "Claro / por supuesto" },
      ],
      fillBlank: {
        title: "Practicá los adjetivos y conectores",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "молодой", transliteration: "molodoy" },
          { ru: "интересный", transliteration: "interesnyy" },
          { ru: "уже", transliteration: "uzhe" },
          { ru: "можно", transliteration: "mozhno" },
          { ru: "конечно", transliteration: "konechno" },
        ],
        sentences: [
          { before: "Мой брат ещё совсем ", answer: "молодой", after: ".", es: "Mi hermano es todavía muy joven." },
          { before: "Это очень ", answer: "интересный", after: " фильм.", es: "Esta película es muy interesante." },
          { before: "Я ", answer: "уже", after: " прочитал роман.", es: "Ya leí la novela." },
          { before: "", answer: "можно", after: " взять книгу?", es: "¿Se puede tomar el libro?" },
          { before: "Ты хочешь чай? — ", answer: "конечно", after: "!", es: "¿Querés té? — ¡Claro!" },
        ],
      },
    },
  ],
};
