export const lesson = {
  slug: "a1-vocab-2",
  level: "A1",
  type: "vocabulary",
  module: "Vocabulario 2",
  order: 6,
  title: "Vocabulario 2",
  topics: [
    {
      title: "Números",
      vocabulary: [
        { ru: "Пять", transliteration: "pyat'", es: "Cinco" },
        { ru: "Два", transliteration: "dva", es: "Dos" },
        { ru: "Шесть", transliteration: "shest'", es: "Seis" },
        { ru: "Семь", transliteration: "sem'", es: "Siete" },
        { ru: "Восемь", transliteration: "vosem'", es: "Ocho" },
        { ru: "Девять", transliteration: "devyat'", es: "Nueve" },
        { ru: "Одиннадцать", transliteration: "odinnadtsat'", es: "Once" },
      ],
      fillBlank: {
        title: "Practicá los números",
        instructions: "Completá cada cuenta con el número correcto.",
        wordBank: [
          { ru: "семь", transliteration: "sem'" },
          { ru: "шесть", transliteration: "shest'" },
          { ru: "восемь", transliteration: "vosem'" },
          { ru: "одиннадцать", transliteration: "odinnadtsat'" },
          { ru: "пять", transliteration: "pyat'" },
          { ru: "два", transliteration: "dva" },
          { ru: "девять", transliteration: "devyat'" },
        ],
        sentences: [
          { before: "2 + 5 = ", answer: "семь", after: ".", es: "2 + 5 = siete." },
          { before: "4 + 2 = ", answer: "шесть", after: ".", es: "4 + 2 = seis." },
          { before: "3 + 5 = ", answer: "восемь", after: ".", es: "3 + 5 = ocho." },
          { before: "9 + 2 = ", answer: "одиннадцать", after: ".", es: "9 + 2 = once." },
          { before: "3 + 2 = ", answer: "пять", after: ".", es: "3 + 2 = cinco." },
          { before: "1 + 1 = ", answer: "два", after: ".", es: "1 + 1 = dos." },
          { before: "4 + 5 = ", answer: "девять", after: ".", es: "4 + 5 = nueve." },
        ],
      },
    },
    {
      title: "Verbos",
      vocabulary: [
        { ru: "Делать", transliteration: "delat'", es: "Hacer" },
        { ru: "Изучать", transliteration: "izuchat'", es: "Estudiar (algo específico)" },
        { ru: "Смотреть", transliteration: "smotret'", es: "Mirar / Ver" },
        { ru: "Гулять", transliteration: "gulyat'", es: "Pasear" },
        { ru: "Стоить", transliteration: "stoit'", es: "Costar" },
        { ru: "Идти", transliteration: "idti", es: "Ir (a pie)" },
        { ru: "Покупать", transliteration: "pokupat'", es: "Comprar" },
      ],
      fillBlank: {
        title: "Practicá los verbos",
        instructions: "Completá cada frase con la forma correcta del verbo.",
        wordBank: [
          { ru: "делает", transliteration: "delayet" },
          { ru: "изучает", transliteration: "izuchayet" },
          { ru: "смотрим", transliteration: "smotrim" },
          { ru: "гуляет", transliteration: "gulyayet" },
          { ru: "идёт", transliteration: "idyot" },
          { ru: "покупает", transliteration: "pokupayet" },
          { ru: "стоит", transliteration: "stoit" },
        ],
        sentences: [
          { before: "Что она ", answer: "делает", after: "?", es: "¿Qué hace ella?" },
          { before: "Студент ", answer: "изучает", after: " русский язык.", es: "El estudiante estudia el idioma ruso." },
          { before: "Вечером мы ", answer: "смотрим", after: ".", es: "Por la noche miramos (la tele)." },
          { before: "Друг ", answer: "гуляет", after: " здесь.", es: "El amigo pasea aquí." },
          { before: "Учитель ", answer: "идёт", after: ".", es: "El maestro va caminando." },
          { before: "Врач ", answer: "покупает", after: " хлеб.", es: "El médico compra pan." },
          { before: "Хлеб ", answer: "стоит", after: " один рубль.", es: "El pan cuesta un rublo." },
        ],
      },
    },
    {
      title: "Sustantivos",
      vocabulary: [
        { ru: "Час", transliteration: "chas", es: "Hora" },
        { ru: "День", transliteration: "den'", es: "Día" },
        { ru: "Чай", transliteration: "chay", es: "Té" },
        { ru: "Коллега", transliteration: "kollega", es: "Colega" },
        { ru: "Язык", transliteration: "yazyk", es: "Idioma / Lengua" },
        { ru: "Хлеб", transliteration: "khleb", es: "Pan" },
        { ru: "Яблоко", transliteration: "yabloko", es: "Manzana" },
        { ru: "Рубль", transliteration: "rubl'", es: "Rublo" },
        { ru: "Овощи", transliteration: "ovoshchi", es: "Verduras" },
        { ru: "Фрукты", transliteration: "frukty", es: "Frutas" },
        { ru: "Помидор", transliteration: "pomidor", es: "Tomate" },
        { ru: "Утро", transliteration: "utro", es: "Mañana (sustantivo)" },
      ],
      fillBlank: {
        title: "Practicá los sustantivos",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "чай", transliteration: "chay" },
          { ru: "хлеб", transliteration: "khleb" },
          { ru: "яблоко", transliteration: "yabloko" },
          { ru: "помидор", transliteration: "pomidor" },
          { ru: "язык", transliteration: "yazyk" },
          { ru: "день", transliteration: "den'" },
          { ru: "утро", transliteration: "utro" },
          { ru: "рубль", transliteration: "rubl'" },
          { ru: "коллега", transliteration: "kollega" },
          { ru: "овощи", transliteration: "ovoshchi" },
        ],
        sentences: [
          { before: "Я пью ", answer: "чай", after: ".", es: "Bebo té." },
          { before: "Я ем ", answer: "хлеб", after: ".", es: "Como pan." },
          { before: "Она ест ", answer: "яблоко", after: ".", es: "Ella come una manzana." },
          { before: "На столе ", answer: "помидор", after: ".", es: "En la mesa hay un tomate." },
          { before: "Я изучаю русский ", answer: "язык", after: ".", es: "Estudio el idioma ruso." },
          { before: "Сегодня хороший ", answer: "день", after: ".", es: "Hoy es un buen día." },
          { before: "Доброе ", answer: "утро", after: "!", es: "¡Buenos días!" },
          { before: "Это стоит один ", answer: "рубль", after: ".", es: "Esto cuesta un rublo." },
          { before: "Мой ", answer: "коллега", after: " работает здесь.", es: "Mi colega trabaja aquí." },
          { before: "Я ем ", answer: "овощи", after: ".", es: "Como verduras." },
        ],
      },
    },
    {
      title: "Adverbios y otras palabras útiles",
      vocabulary: [
        { ru: "Когда", transliteration: "kogda", es: "Cuándo" },
        { ru: "Здорово", transliteration: "zdorovo", es: "¡Qué bien!" },
        { ru: "Много", transliteration: "mnogo", es: "Mucho" },
        { ru: "Каждый", transliteration: "kazhdyy", es: "Cada" },
        { ru: "Здравствуйте", transliteration: "zdrastvuyte", es: "Hola (formal)" },
        { ru: "Сколько", transliteration: "skol'ko", es: "Cuánto" },
        { ru: "Сегодня", transliteration: "segodnya", es: "Hoy" },
        { ru: "Недалеко", transliteration: "nedaleko", es: "No lejos / Cerca" },
        { ru: "Всё", transliteration: "vsyo", es: "Todo" },
        { ru: "Дорого", transliteration: "dorogo", es: "Caro" },
        { ru: "Отлично", transliteration: "otlichno", es: "Excelente" },
      ],
      fillBlank: {
        title: "Practicá los adverbios y palabras útiles",
        instructions: "Completá cada frase con la palabra correcta.",
        wordBank: [
          { ru: "дорого", transliteration: "dorogo" },
          { ru: "отлично", transliteration: "otlichno" },
          { ru: "здравствуйте", transliteration: "zdrastvuyte" },
          { ru: "когда", transliteration: "kogda" },
          { ru: "сколько", transliteration: "skol'ko" },
          { ru: "каждый", transliteration: "kazhdyy" },
          { ru: "недалеко", transliteration: "nedaleko" },
          { ru: "много", transliteration: "mnogo" },
          { ru: "всё", transliteration: "vsyo" },
        ],
        sentences: [
          { before: "Это очень ", answer: "дорого", after: ".", es: "Esto es muy caro." },
          { before: "Ты играешь ", answer: "отлично", after: "!", es: "¡Tocas excelente!" },
          { before: "", answer: "здравствуйте", after: "! Как дела?", es: "¡Hola! ¿Cómo estás?" },
          { before: "", answer: "когда", after: " ты идёшь?", es: "¿Cuándo vas?" },
          { before: "", answer: "сколько", after: " стоит хлеб?", es: "¿Cuánto cuesta el pan?" },
          { before: "", answer: "каждый", after: " день я пью чай.", es: "Cada día bebo té." },
          { before: "Это ", answer: "недалеко", after: ".", es: "Esto está cerca." },
          { before: "Мы гуляем ", answer: "много", after: ".", es: "Paseamos mucho." },
          { before: "", answer: "всё", after: " хорошо!", es: "¡Todo bien!" },
        ],
      },
    },
  ],
};
